require('dotenv').config();

const discordColors = [
    { name: 'Default', value: '#000000' },
    { name: 'Aqua', value: '#1ABC9C' },
    { name: 'DarkAqua', value: '#11806A' },
    { name: 'Green', value: '#57F287' },
    { name: 'DarkGreen', value: '#1F8B4C' },
    { name: 'Blue', value: '#3498DB' },
    { name: 'DarkBlue', value: '#206694' },
    { name: 'Purple', value: '#9B59B6' },
    { name: 'DarkPurple', value: '#71368A' },
    { name: 'LuminousVividPink', value: '#E91E63' },
    { name: 'DarkVividPink', value: '#AD1457' },
    { name: 'Gold', value: '#F1C40F' },
    { name: 'DarkGold', value: '#C27C0E' },
    { name: 'Orange', value: '#E67E22' },
    { name: 'DarkOrange', value: '#A84300' },
    { name: 'Red', value: '#ED4245' },
    { name: 'DarkRed', value: '#992D22' },
    { name: 'Grey', value: '#95A5A6' },
    { name: 'DarkGrey', value: '#979C9F' },
    { name: 'DarkerGrey', value: '#7F8C8D' },
    { name: 'LightGrey', value: '#BCC0C0' },
    { name: 'Navy', value: '#34495E' },
    { name: 'DarkNavy', value: '#2C3E50' },
    { name: 'Yellow', value: '#FFFF00' },
];

const admins = process.env.ADMINS ? process.env.ADMINS.split(',') : ['Admins not included in the files'];
const goodRoles = process.env.GOOD_ROLES ? process.env.GOOD_ROLES.split(',') : ['Roles not included in the files'];
function hasGoodRole(user) {
    return goodRoles.some(role => user.roles.cache.has(role));
}

const virusTotalAPIKey = process.env.VIRUSTOTAL_API_KEY;

const countries = [
    { name: 'Afghanistan', value: 'Kabul', continent: 'Asia' },
    { name: 'Aland Islands', value: 'Mariehamn', continent: 'Europe' },
    { name: 'Albania', value: 'Tirana', continent: 'Europe' },
    { name: 'Algeria', value: 'Algiers', continent: 'Africa' },
    { name: 'American Samoa', value: 'Pago Pago', continent: 'Oceania' },
    { name: 'Andorra', value: 'Andorra la Vella', continent: 'Europe' },
    { name: 'Angola', value: 'Luanda', continent: 'Africa' },
    { name: 'Anguilla', value: 'The Valley', continent: 'North America' },
    {name: 'Antigua and Barbuda', value: 'St. Johns', continent: 'North America' },
    { name: 'Argentina', value: 'Buenos Aires', continent: 'South America' },
    { name: 'Armenia', value: 'Yerevan', continent: 'Asia' },
    { name: 'Aruba', value: 'Oranjestad', continent: 'South America' },
    { name: 'Ascension Island', value: 'Georgetown', continent: 'Africa' },
    { name: 'Australia', value: 'Canberra', continent: 'Oceania' },
    { name: 'Austria', value: 'Vienna', continent: 'Europe' },
    { name: 'Azerbaijan', value: 'Baku', continent: 'Asia' },
    { name: 'Bahamas', value: 'Nassau', continent: 'North America' },
    { name: 'Bahrain', value: 'Manama', continent: 'Asia' },
    { name: 'Bangladesh', value: 'Dhaka', continent: 'Asia' },
    { name: 'Barbados', value: 'Bridgetown', continent: 'North America' },
    { name: 'Belarus', value: 'Minsk', continent: 'Europe' },
    { name: 'Belgium', value: 'Brussels', continent: 'Europe' },
    { name: 'Belize', value: 'Belmopan', continent: 'North America' },
    { name: 'Benin', value: 'Porto-Novo', continent: 'Africa' },
    { name: 'Bermuda', value: 'Hamilton', continent: 'North America' },
    { name: 'Bhutan', value: 'Thimphu', continent: 'Asia' },
    { name: 'Bolivia', value: 'Sucre', continent: 'South America' },
    { name: 'Bonaire, Sint Eustatius and Saba', value: 'Kralendijk', continent: 'South America' },
    { name: 'Bosnia and Herzegovina', value: 'Sarajevo', continent: 'Europe' },
    { name: 'Botswana', value: 'Gaborone', continent: 'Africa' },
    { name: 'Brazil', value: 'Brasília', continent: 'South America' },
    { name: 'British Indian Ocean Territory', value: 'Diego Garcia', continent: 'Asia' },
    { name: 'Brunei Darussalam', value: 'Bandar Seri Begawan', continent: 'Asia' },
    { name: 'Bulgaria', value: 'Sofia', continent: 'Europe' },
    { name: 'Burkina Faso', value: 'Ouagadougou', continent: 'Africa' },
    { name: 'Burundi', value: 'Bujumbura', continent: 'Africa' },
    { name: 'Cabo Verde', value: 'Praia', continent: 'Africa' },
    { name: 'Cambodia', value: 'Phnom Penh', continent: 'Asia' },
    { name: 'Cameroon', value: 'Yaoundé', continent: 'Africa' },
    { name: 'Canada', value: 'Ottawa', continent: 'North America' },
    { name: 'Cayman Islands', value: 'George Town', continent: 'North America' },
    { name: 'Central African Republic', value: 'Bangui', continent: 'Africa' },
    {name: 'Chad', value: 'NDjamena', continent: 'Africa' },
    { name: 'Chile', value: 'Santiago', continent: 'South America' },
    { name: 'China', value: 'Beijing', continent: 'Asia' },
    { name: 'Christmas Island', value: 'Flying Fish Cove', continent: 'Asia' },
    { name: 'Cocos (Keeling) Islands', value: 'West Island', continent: 'Asia' },
    { name: 'Colombia', value: 'Bogotá', continent: 'South America' },
    { name: 'Comoros', value: 'Moroni', continent: 'Africa' },
    { name: 'Cook Islands', value: 'Avarua', continent: 'Oceania' },
    { name: 'Costa Rica', value: 'San José', continent: 'North America' },
    { name: 'Croatia', value: 'Zagreb', continent: 'Europe' },
    { name: 'Cuba', value: 'Havana', continent: 'North America' },
    { name: 'Curaçao', value: 'Willemstad', continent: 'South America' },
    { name: 'Cyprus', value: 'Nicosia', continent: 'Europe' },
    { name: 'Czech Republic', value: 'Prague', continent: 'Europe' },
    {name: 'Côte dIvoire', value: 'Yamoussoukro', continent: 'Africa' },
    { name: 'Democratic Republic of the Congo', value: 'Kinshasa', continent: 'Africa' },
    { name: 'Denmark', value: 'Copenhagen', continent: 'Europe' },
    { name: 'Djibouti', value: 'Djibouti', continent: 'Africa' },
    { name: 'Dominica', value: 'Roseau', continent: 'North America' },
    { name: 'Dominican Republic', value: 'Santo Domingo', continent: 'North America' },
    { name: 'Ecuador', value: 'Quito', continent: 'South America' },
    { name: 'Egypt', value: 'Cairo', continent: 'Africa' },
    { name: 'El Salvador', value: 'San Salvador', continent: 'North America' },
    { name: 'England', value: 'London', continent: 'Europe' },
    { name: 'Equatorial Guinea', value: 'Malabo', continent: 'Africa' },
    { name: 'Eritrea', value: 'Asmara', continent: 'Africa' },
    { name: 'Estonia', value: 'Tallinn', continent: 'Europe' },
    { name: 'Eswatini', value: 'Lobamba, Mbabane', continent: 'Africa' },
    { name: 'Ethiopia', value: 'Addis Ababa', continent: 'Africa' },
    { name: 'Falkland Islands', value: 'Stanley', continent: 'South America' },
    { name: 'Faroe Islands', value: 'Tórshavn', continent: 'Europe' },
    { name: 'Federated States of Micronesia', value: 'Palikir', continent: 'Oceania' },
    { name: 'Fiji', value: 'Suva', continent: 'Oceania' },
    { name: 'Finland', value: 'Helsinki', continent: 'Europe' },
    { name: 'France', value: 'Paris', continent: 'Europe' },
    { name: 'French Guiana', value: 'Cayenne', continent: 'South America' },
    { name: 'French Polynesia', value: 'Papeete', continent: 'Oceania' },
    { name: 'French Southern Territories', value: 'Saint-Pierre, Réunion', continent: 'Africa' },
    { name: 'Gabon', value: 'Libreville', continent: 'Africa' },
    { name: 'Gambia', value: 'Banjul', continent: 'Africa' },
    { name: 'Georgia', value: 'Tbilisi', continent: 'Asia' },
    { name: 'Germany', value: 'Berlin', continent: 'Europe' },
    { name: 'Ghana', value: 'Accra', continent: 'Africa' },
    { name: 'Gibraltar', value: 'Gibraltar', continent: 'Europe' },
    { name: 'Greece', value: 'Athens', continent: 'Europe' },
    { name: 'Greenland', value: 'Nuuk', continent: 'North America' },
    {name: 'Grenada', value: 'St. Georges', continent: 'North America' },
    { name: 'Guadeloupe', value: 'Basse-Terre', continent: 'North America' },
    { name: 'Guam', value: 'Hagåtña', continent: 'Oceania' },
    { name: 'Guatemala', value: 'Guatemala City', continent: 'North America' },
    { name: 'Guernsey', value: 'Saint Peter Port', continent: 'Europe' },
    { name: 'Guinea', value: 'Conakry', continent: 'Africa' },
    { name: 'Guinea-Bissau', value: 'Bissau', continent: 'Africa' },
    { name: 'Guyana', value: 'Georgetown', continent: 'South America' },
    { name: 'Haiti', value: 'Port-au-Prince', continent: 'North America' },
    { name: 'Holy See', value: 'Vatican City', continent: 'Europe' },
    { name: 'Honduras', value: 'Tegucigalpa', continent: 'North America' },
    { name: 'Hong Kong', value: 'Hong Kong', continent: 'Asia' },
    { name: 'Hungary', value: 'Budapest', continent: 'Europe' },
    { name: 'Iceland', value: 'Reykjavik', continent: 'Europe' },
    { name: 'India', value: 'New Delhi', continent: 'Asia' },
    { name: 'Indonesia', value: 'Jakarta', continent: 'Asia' },
    { name: 'Iran', value: 'Tehran', continent: 'Asia' },
    { name: 'Iraq', value: 'Baghdad', continent: 'Asia' },
    { name: 'Ireland', value: 'Dublin', continent: 'Europe' },
    { name: 'Isle of Man', value: 'Douglas', continent: 'Europe' },
    { name: 'Israel', value: 'Jerusalem', continent: 'Asia' },
    { name: 'Italy', value: 'Rome', continent: 'Europe' },
    { name: 'Jamaica', value: 'Kingston', continent: 'North America' },
    { name: 'Japan', value: 'Tokyo', continent: 'Asia' },
    { name: 'Jersey', value: 'Saint Helier', continent: 'Europe' },
    { name: 'Jordan', value: 'Amman', continent: 'Asia' },
    { name: 'Kazakhstan', value: 'Astana', continent: 'Asia' },
    { name: 'Kenya', value: 'Nairobi', continent: 'Africa' },
    { name: 'Kiribati', value: 'South Tarawa', continent: 'Oceania' },
    { name: 'Kosovo', value: 'Pristina', continent: 'Europe' },
    { name: 'Kuwait', value: 'Kuwait City', continent: 'Asia' },
    { name: 'Kyrgyzstan', value: 'Bishkek', continent: 'Asia' },
    { name: 'Laos', value: 'Vientiane', continent: 'Asia' },
    { name: 'Latvia', value: 'Riga', continent: 'Europe' },
    { name: 'Lebanon', value: 'Beirut', continent: 'Asia' },
    { name: 'Lesotho', value: 'Maseru', continent: 'Africa' },
    { name: 'Liberia', value: 'Monrovia', continent: 'Africa' },
    { name: 'Libya', value: 'Tripoli', continent: 'Africa' },
    { name: 'Liechtenstein', value: 'Vaduz', continent: 'Europe' },
    { name: 'Lithuania', value: 'Vilnius', continent: 'Europe' },
    { name: 'Luxembourg', value: 'Luxembourg City', continent: 'Europe' },
    { name: 'Macau', value: 'Macau', continent: 'Asia' },
    { name: 'Madagascar', value: 'Antananarivo', continent: 'Africa' },
    { name: 'Malawi', value: 'Lilongwe', continent: 'Africa' },
    { name: 'Malaysia', value: 'Kuala Lumpur', continent: 'Asia' },
    { name: 'Maldives', value: 'Malé', continent: 'Asia' },
    { name: 'Mali', value: 'Bamako', continent: 'Africa' },
    { name: 'Malta', value: 'Valletta', continent: 'Europe' },
    { name: 'Marshall Islands', value: 'Majuro', continent: 'Oceania' },
    { name: 'Martinique', value: 'Fort-de-France', continent: 'North America' },
    { name: 'Mauritania', value: 'Nouakchott', continent: 'Africa' },
    { name: 'Mauritius', value: 'Port Louis', continent: 'Africa' },
    { name: 'Mayotte', value: 'Mamoudzou', continent: 'Africa' },
    { name: 'Mexico', value: 'Mexico City', continent: 'North America' },
    { name: 'Moldova', value: 'Chișinău', continent: 'Europe' },
    { name: 'Monaco', value: 'Monaco', continent: 'Europe' },
    { name: 'Mongolia', value: 'Ulaanbaatar', continent: 'Asia' },
    { name: 'Montenegro', value: 'Podgorica', continent: 'Europe' },
    { name: 'Montserrat', value: 'Little Bay, Brades, Plymouth', continent: 'North America' },
    { name: 'Morocco', value: 'Rabat', continent: 'Africa' },
    { name: 'Mozambique', value: 'Maputo', continent: 'Africa' },
    { name: 'Myanmar', value: 'Naypyidaw', continent: 'Asia' },
    { name: 'Namibia', value: 'Windhoek', continent: 'Africa' },
    { name: 'Nauru', value: 'Yaren District', continent: 'Oceania' },
    { name: 'Nepal', value: 'Kathmandu', continent: 'Asia' },
    { name: 'Netherlands', value: 'Amsterdam', continent: 'Europe' },
    { name: 'New Caledonia', value: 'Nouméa', continent: 'Oceania' },
    { name: 'New Zealand', value: 'Wellington', continent: 'Oceania' },
    { name: 'Nicaragua', value: 'Managua', continent: 'North America' },
    { name: 'Niger', value: 'Niamey', continent: 'Africa' },
    { name: 'Nigeria', value: 'Abuja', continent: 'Africa' },
    { name: 'Niue', value: 'Alofi', continent: 'Oceania' },
    { name: 'Norfolk Island', value: 'Kingston', continent: 'Oceania' },
    { name: 'North Korea', value: 'Pyongyang', continent: 'Asia' },
    { name: 'North Macedonia', value: 'Skopje', continent: 'Europe' },
    { name: 'Northern Ireland', value: 'Belfast', continent: 'Europe' },
    { name: 'Northern Mariana Islands', value: 'Saipan', continent: 'Oceania' },
    { name: 'Norway', value: 'Oslo', continent: 'Europe' },
    { name: 'Oman', value: 'Muscat', continent: 'Asia' },
    { name: 'Pakistan', value: 'Islamabad', continent: 'Asia' },
    { name: 'Palau', value: 'Ngerulmud', continent: 'Oceania' },
    { name: 'Panama', value: 'Panama City', continent: 'North America' },
    { name: 'Papua New Guinea', value: 'Port Moresby', continent: 'Oceania' },
    { name: 'Paraguay', value: 'Asunción', continent: 'South America' },
    { name: 'Peru', value: 'Lima', continent: 'South America' },
    { name: 'Philippines', value: 'Manila', continent: 'Asia' },
    { name: 'Pitcairn', value: 'Adamstown', continent: 'Oceania' },
    { name: 'Poland', value: 'Warsaw', continent: 'Europe' },
    { name: 'Portugal', value: 'Lisbon', continent: 'Europe' },
    { name: 'Puerto Rico', value: 'San Juan', continent: 'North America' },
    { name: 'Qatar', value: 'Doha', continent: 'Asia' },
    { name: 'Republic of the Congo', value: 'Brazzaville', continent: 'Africa' },
    { name: 'Romania', value: 'Bucharest', continent: 'Europe' },
    { name: 'Russia', value: 'Moscow', continent: 'Europe' },
    { name: 'Rwanda', value: 'Kigali', continent: 'Africa' },
    { name: 'Réunion', value: 'Saint-Denis', continent: 'Africa' },
    { name: 'Saint Barthélemy', value: 'Gustavia', continent: 'North America' },
    { name: 'Saint Helena', value: 'Jamestown', continent: 'Africa' },
    { name: 'Saint Helena, Ascension and Tristan da Cunha', value: 'Jamestown', continent: 'Africa' },
    { name: 'Saint Kitts and Nevis', value: 'Basseterre', continent: 'North America' },
    { name: 'Saint Lucia', value: 'Castries', continent: 'North America' },
    { name: 'Saint Martin', value: 'Marigot', continent: 'North America' },
    { name: 'Saint Pierre and Miquelon', value: 'Saint-Pierre', continent: 'North America' },
    { name: 'Saint Vincent and the Grenadines', value: 'Kingstown', continent: 'North America' },
    { name: 'Samoa', value: 'Apia', continent: 'Oceania' },
    { name: 'San Marino', value: 'San Marino', continent: 'Europe' },
    { name: 'Sao Tome and Principe', value: 'São Tomé', continent: 'Africa' },
    { name: 'Saudi Arabia', value: 'Riyadh', continent: 'Asia' },
    { name: 'Scotland', value: 'Edinburgh', continent: 'Europe' },
    { name: 'Senegal', value: 'Dakar', continent: 'Africa' },
    { name: 'Serbia', value: 'Belgrade', continent: 'Europe' },
    { name: 'Seychelles', value: 'Victoria', continent: 'Africa' },
    { name: 'Sierra Leone', value: 'Freetown', continent: 'Africa' },
    { name: 'Singapore', value: 'Singapore', continent: 'Asia' },
    { name: 'Sint Maarten', value: 'Philipsburg', continent: 'North America' },
    { name: 'Slovakia', value: 'Bratislava', continent: 'Europe' },
    { name: 'Slovenia', value: 'Ljubljana', continent: 'Europe' },
    { name: 'Solomon Islands', value: 'Honiara', continent: 'Oceania' },
    { name: 'Somalia', value: 'Mogadishu', continent: 'Africa' },
    { name: 'South Africa', value: 'Pretoria', continent: 'Africa' },
    { name: 'South Georgia and the South Sandwich Islands', value: 'King Edward Point', continent: 'Antarctica' },
    { name: 'South Korea', value: 'Seoul', continent: 'Asia' },
    { name: 'South Sudan', value: 'Juba', continent: 'Africa' },
    { name: 'Spain', value: 'Madrid', continent: 'Europe' },
    { name: 'Sri Lanka', value: 'Sri Jayawardenepura Kotte, Colombo', continent: 'Asia' },
    { name: 'State of Palestine', value: 'Ramallah', continent: 'Asia' },
    { name: 'Sudan', value: 'Khartoum', continent: 'Africa' },
    { name: 'Suriname', value: 'Paramaribo', continent: 'South America' },
    { name: 'Svalbard and Jan Mayen', value: 'Longyearbyen', continent: 'Europe' },
    { name: 'Sweden', value: 'Stockholm', continent: 'Europe' },
    { name: 'Switzerland', value: 'Bern', continent: 'Europe' },
    { name: 'Syria', value: 'Damascus', continent: 'Asia' },
    { name: 'Taiwan', value: 'Taipei', continent: 'Asia' },
    { name: 'Tajikistan', value: 'Dushanbe', continent: 'Asia' },
    { name: 'Tanzania', value: 'Dodoma', continent: 'Africa' },
    { name: 'Thailand', value: 'Bangkok', continent: 'Asia' },
    { name: 'Timor-Leste', value: 'Dili', continent: 'Asia' },
    { name: 'Togo', value: 'Lomé', continent: 'Africa' },
    { name: 'Tokelau', value: 'Nukunonu, Atafu,Tokelau', continent: 'Oceania' },
    { name: 'Tonga', value: 'Nukuʻalofa', continent: 'Oceania' },
    { name: 'Trinidad and Tobago', value: 'Port of Spain', continent: 'South America' },
    { name: 'Tristan da Cunha', value: 'Edinburgh of the Seven Seas', continent: 'Africa' },
    { name: 'Tunisia', value: 'Tunis', continent: 'Africa' },
    { name: 'Turkmenistan', value: 'Ashgabat', continent: 'Asia' },
    { name: 'Turks and Caicos Islands', value: 'Cockburn Town', continent: 'North America' },
    { name: 'Tuvalu', value: 'Funafuti', continent: 'Oceania' },
    { name: 'Türkiye', value: 'Ankara', continent: 'Asia' },
    { name: 'Uganda', value: 'Kampala', continent: 'Africa' },
    { name: 'Ukraine', value: 'Kiev', continent: 'Europe' },
    { name: 'United Arab Emirates', value: 'Abu Dhabi', continent: 'Asia' },
    { name: 'United Kingdom', value: 'London', continent: 'Europe' },
    { name: 'United States Minor Outlying Islands', value: 'Washington, D.C.', continent: 'North America' },
    { name: 'United States of America', value: 'Washington, D.C.', continent: 'North America' },
    { name: 'Uruguay', value: 'Montevideo', continent: 'South America' },
    { name: 'Uzbekistan', value: 'Tashkent', continent: 'Asia' },
    { name: 'Vanuatu', value: 'Port Vila', continent: 'Oceania' },
    { name: 'Venezuela', value: 'Caracas', continent: 'South America' },
    { name: 'Vietnam', value: 'Hanoi', continent: 'Asia' },
    { name: 'Virgin Islands (British)', value: 'Road Town', continent: 'North America' },
    { name: 'Virgin Islands (U.S.)', value: 'Charlotte Amalie', continent: 'North America' },
    { name: 'Wales', value: 'Cardiff', continent: 'Europe' },
    { name: 'Wallis and Futuna', value: 'Mata-Utu', continent: 'Oceania' },
    { name: 'Western Sahara', value: 'Laayoune', continent: 'Africa' },
    {name: 'Yemen', value: 'Sanaa', continent: 'Asia' },
    { name: 'Zambia', value: 'Lusaka', continent: 'Africa' },
    { name: 'Zimbabwe', value: 'Harare', continent: 'Africa' },
];

module.exports = {
    discordColors,
    countries,
    goodRoles,
    hasGoodRole,
    admins,
    virusTotalAPIKey,
};
